### ISSUE TITLE
bounding box to select cells

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#112]
It can be super hard to select very small cells/a single pixel that gets accidentally created. Having the option to select label IDs with a bounding box could help address this use case.

**Comment by geneva-miller** [comment]
I'll note that zoom should also help with this when I am able to merge that into RGB.

Is this something where you want to select a label or remove it? This could pair nicely with #102. Eg, remove all small objects from frame with certain keybind, fill small holes on a per label basis if needed. If the use case is selection then I think zoom is likely the way to go.

**Comment by ngreenwald** [comment]
Definitely. The use case is there's a tiny label, 1-2 pixels, in the center of another cell. Sometimes as a result of a failed watershed, sometimes from poor post-processing. 

Removing all small objects -> hole filling would be great!

**Comment by geneva-miller** [comment]
Between zooming and using keybinds to cycle the selected label, it is now much easier to select small labels in DCL. The watershed action, which was responsible for introducing single-pixel labels, has also been updated to avoid that behavior. (Very small labels are slightly dilated as part of the action to make them easier to click on.)

I think "removing small objects from a frame" and "filling the holes within a selected label" would both be nice additions to the available actions, so I'm leaving this issue open for the time being.
