### ISSUE TITLE
adjustable RGB+CMY channels in browser

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#127]
Currently, the initial version of RGB browser caliban will not allow users to adjust channels individually. This is largely because the raw image payload delivered by the server will be a single RGB, composed of up to 6 adjusted channels collapsed into an output image. Adjusting the image would either require server calls (adjust individual channels) or could change R, G, and B values (but this would mess with any potential CMY channel info), so it is not implemented. This should be sufficient for many annotation needs, especially for images that have only 2 or 3 channels.

However, future browser users may want the ability to adjust the brightness of each channel independently, as it exists in desktop. In that case, we could modify the payload to include up to 2 RGB images, one to correspond to the first three channels and the other to contain CMY info. The CMY "RGB" image channels could then be adjusted independently and applied to the displayed image with CMY values.

**Comment by ngreenwald** [comment]
I think this would be a nice advanced feature to have. It if it's easier to implement, even just the option to turn certain channels on and off would be helpful.

**Comment by ngreenwald** [comment]
So as we've started to move forward with internal caliban-desktop jobs, it's become clear how crucial the 'o' hotkey to turn channels on and off is. As we get ready to start doing test jobs for MIBI data over the next few weeks I think this is going to be a must-have feature.

An annotator friendly version of this for browser might be having hotkeys 1-3 correspond to each channel, and pressing the hotkey turns the channel on or off? Or we could keep the current hotkeys of 'c' to cycle through channels and 'o' to toggle currently selected channel. I don't have any insight as to which of these options would be easiest to implement, or easiest to explain to the annotators.

**Comment by geneva-miller** [comment]
The image processing step that turns channels on or off should be fairly straightforward to do, although we would not be able to do any kind of CMY adjustment for now, only RGB. 

My concern is that the keybind-based toggles would be somewhat easy to implement, but make it more difficult for annotators to learn and remember how to interact with the image in all the different ways they need to. From a usability standpoint, I would most like to implement this with checkboxes that annotators could toggle, either in the infopane itself or on a toolbar right above the canvas. @willgraf what are your thoughts on feasibility of checkbox implementation vs. keybinds for now?

**Comment by ngreenwald** [comment]
I'm equally happy with any of those options, whatever you think is best

**Comment by willgraf** [comment]
I think checkboxes would be better, as i'm a little overwhelmed with all the keybindings.

That said, if we are going to make a checkbox setup, we should probably figure out what other functionality should go in there as well.

**Comment by geneva-miller** [comment]
Could you clarify "other functionality"? For this in particular I'm envisioning adding three checkboxes (R, G, and B) to modulate the raw image display, perhaps extending it to (up to) six checkboxes in the future to cover CMY as well.

**Comment by willgraf** [comment]
If we're building the checkbox infrastructure, we should figure out what else we can move over as checkboxes. That way we can probably save some time in future work.

**Comment by ngreenwald** [comment]
If we're opening it up to GUIs in general, having buttons to turn erase mode on and off, and color picker would be nice to remove the number of hotkeys annotators have to remember.

**Comment by geneva-miller** [comment]
Oh, there's plenty of GUI elements I'd like to add to Caliban over time. (Brightness/contrast sliders, arrow buttons for moving between frames, channels, slices, etc, zoom in/out buttons, that type of thing.) But specifically with checkboxes, the main other "checkbox" that comes to mind would perhaps be for the brush eraser, and I think that might be more intuitive as a toggle switch. (Although... perhaps the R/G/B toggles could be switches also.)

I don't think we're in a huge rush to convert some of the existing keybinds into GUI elements, or even necessarily to supplement them at the moment. But if we are going to add in rgb channel toggling (which we should, soon) I think it would make the most sense to implement it with checkboxes/toggle switches from the start.

**Comment by willgraf** [comment]
I believe this issue will be fixed by #243 and #248, as they introduce dynamic range for each channel.

**Comment by ngreenwald** [comment]
Yup, this is already working for the prototype Tom had me try out

**Comment by willgraf** [comment]
Closed by #248
