### ISSUE TITLE
Dynamic resizing of HTML for image

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#131]
I spoke with Geneva about this already, neither of us was sure what the best way to approach this would be. 

Currently, only a small portion of the screen is actually showing the imaging data. If there was a way so that the image could be more intelligently resized, I think this would increase the speed of annotations significantly, and make them more accurate, especially in tissue. 

![image](https://user-images.githubusercontent.com/13770365/77978037-e5e72800-72b5-11ea-963d-88bb9ab0766c.png)

**Comment by willgraf** [comment]
While #131 goes a long way toward fixing this, I think there is some more improvements we can make. Currently, the page is fitted to the available window shape when loaded, but if the window screen is changed, the canvas is not changed with it.

I hope I can fix this in #154 by using a modern CSS framework to handle our resizing for us.

**Comment by willgraf** [comment]
Was this resolved?

**Comment by geneva-miller** [comment]
It's been resolved for npzs for a while but we haven't really touched the trk implementation. So, no, not totally resolved

**Comment by ngreenwald** [comment]
This is what I see when opening a job. It seems like most of the problem is with the iframe. I'm not sure if we have control over that. But in general, not much of the real estate is actually the image data. 

I think addressing #132 could help free up some space as well

![image](https://user-images.githubusercontent.com/13770365/87362393-622f0f80-c523-11ea-8bd1-9f6909730666.png)
