### ISSUE TITLE
Remove unnecessary display text for RGB

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#132]
Since RGB mode right now it being used just for 2D data, it would make the UI much cleaner if we removed the extra information that's only relevant for 3D data. 

In particular, I think all of these can be removed:
Frame, channel, feature, highlight cells, highlighted cells, slices

**Comment by geneva-miller** [comment]
I'm on the fence about highlight/highlighting cells, since the translucent highlighting is enabled for RGB mode. (It's somewhat hard to see against the very bright image.) I'd be fine with forcing highlighting always on and then not displaying that it's on, though.

**Comment by ngreenwald** [comment]
Definitely!

**Comment by ngreenwald** [comment]
If you could also remove references to frames in the State prompts that would be great

**Comment by geneva-miller** [comment]
I'm thinking this one won't be in the first round of RGB tweaks. It's conceptually simple but will require some deeper restructuring of the current html to do nicely. I'm looking into how to add it so we don't regret it later

**Comment by ngreenwald** [comment]
Yup, totally fine!

**Comment by ngreenwald** [comment]
Inspired by the poor performance of our first round of annotations, I'm going full Marie Kondo and trying to remove everything that isn't absolutely essential. 

I think switching to brush only mode is a great idea. Here's whats currently displayed:

![image](https://user-images.githubusercontent.com/13770365/78842065-e10c2d80-79b3-11ea-9e21-da8e8da2141c.png)

I think we can hide everything except editing label, eraser, and state.

**Comment by geneva-miller** [comment]
I'm thinking this could be more general than for just rgb mode. Eg, if a file only has 1 frame (always true for RGB, sometimes true for not-RGB), hide the "frame" display, etc. These changes could be applied any time after [load_file is called in start_caliban](https://github.com/vanvalenlab/caliban/blob/browser/develop/browser/static/js/main_zstack.js#L1096).

As mentioned in #143 it would also be nice to change the "edit mode:" html from showing [ON/OFF](https://github.com/vanvalenlab/caliban/blob/browser/develop/browser/static/js/main_zstack.js#L685) to showing "pixels"/"whole labels"

**Comment by willgraf** [comment]
This will be fixed by #243 and #248
