### ISSUE TITLE
Variable lag times

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#142]
The amount of lag between action clicks seems to be variable in Figure8. Last night around 5 PM it was around 0.75 seconds after each action. Now it's closer 0.25 or 0.5 seconds, which is much less noticeable. 

Not sure what the difference is due to, but it makes a fairly significant difference for user experience.

**Comment by willgraf** [comment]
It seems like `pngify` when `raw is True` takes up a huge amount of the processing time.

```
unpickled in 0.0011313589999986107s
pngify raw=False 0.06804040800000166s
pngify raw=True 0.2235789859999926s
got array in 0.009070264000001771s
built payload in 0.014699645999996847s
```

**Comment by willgraf** [comment]
For the `handle_draw` functions, it looks like response time is dominated by the database operations, primarily the update call:

```
loaded JSON payload in 0.0003535010000064176 s
Got project from DB in 0.01933338500001014 s
Action handle_draw finished in 0.00506084299999543 s
Updated project in DB in 0.05887206099998821 s
[2020-05-07 12:21:10,087]:[DEBUG]:[application]: Action "handle_draw" for project "113" finished in 0.0869293020000157 s.
```

**Comment by geneva-miller** [comment]
Re: `get_frame` I think this could be largely addressed by splitting out the cases where the raw or annotated image needs to be updated (#126). Especially for RGB mode, where the raw image never needs to be updated from the server (at least for now, while jobs are single-frame), the speed of `pngify` wouldn't change much.

Re: `handle_draw` I'll note that action time may increase as image size/amount of drawing increases, but for the image sizes that we're working with (approx 500x500 or smaller) this is not likely to be an issue, and may always be trivial compared to db operations.

**Comment by willgraf** [comment]
> Re: `get_frame` I think this could be largely addressed by splitting out the cases where the raw or annotated image needs to be updated (#126). Especially for RGB mode, where the raw image never needs to be updated from the server (at least for now, while jobs are single-frame), the speed of `pngify` wouldn't change much.

Yeah the slowness was specifically for the raw RGB images, so eliminating those unnecessary calls will help. That said, `pngify` can be singificantly improved for these cases by using `PIL`:

```python
def pngify(imgarr, vmin, vmax, cmap):
    out = io.BytesIO()
    if cmap is None:
        img = Image.fromarray(imgarr)
        img.save(out, format="png")
    else:
        plt.imsave(out, imgarr,
                   vmin=vmin,
                   vmax=vmax,
                   cmap=cmap,
                   format="png")
    out.seek(0)
    return out
```

this reduces the raw+rgb `get_frame` calls by ~75%. I'll submit this in a PR eventually when I'm done debugging.

> Re: `handle_draw` I'll note that action time may increase as image size/amount of drawing increases, but for the image sizes that we're working with (approx 500x500 or smaller) this is not likely to be an issue, and may always be trivial compared to db operations.

Yes, I think the `db.commit` takes up the largest fraction of the db time as well. We should think about ways of making the `state` blob easier to send/receive from the db.

**Comment by geneva-miller** [comment]
One thing I've been thinking about is potentially storing the raw, annotated, and "state" data separately, especially if some of the methods can be decoupled from the stored objects. Then only the relevant parts of the file would need to be grabbed for interaction (eg, we don't need any information about the raw image in order to use the brush). This would require breaking changes though so I don't think it should be the first thing we try.

**Comment by willgraf** [comment]
I tested out removing the `raw` response from the `/action` payload (now #166). I can't be sure this is "solving" the issue though.  With this change, the biggest issues for response time are:

1. calling `pngify` on the label mask. (~30% of time)
2. updating the DB (40%)
3. fetching from the DB (10%)
_*calculated by a few replace / delete actions_

I think the blame rests with the BLOB type we get from the DB on each action.


I imagine that if we could somehow better compress the "state" object it would resolve much of our DB issues.

**Comment by MekWarrior** [comment]
Stale issue. Closing in response to backend updates and sunsetting of js version in favor of React.
