### ISSUE TITLE
Hodgepodge of lower priority changes

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#143]
Here's the notes I made to myself while running through the latest version. 

- [x] The links to Github and DeepCell at the top of browser caliban don't work. 
- [x] It would be nice to have an optional comment box for annotators to fill out with suggestions/issues
- [ ] The current color map isn't great, and it's hard to differentiate neighboring cells with similar values
- [ ] It would be nice to add label view to "edit" mode 
- [x] It would be nice to change the name from "edit" mode to instead be either pixel edit or label edit

**Comment by geneva-miller** [comment]
Note on the "links" at the top of the page: I would want a way to disable these as well so annotators don't accidentally leave the file they are working on.

**Comment by willgraf** [comment]
No need to disable the links, we can just give them a [blank target](https://www.w3schools.com/tags/att_a_target.asp) so they open in a new window.

**Comment by geneva-miller** [comment]
Re: colormap, I think I'm inclined to use the colormap option I showed in #74, but I would also have to change the highlighting method, since a solid red label would no longer stand out. I'm thinking a white outline around the border of the label? I could add this to desktop RGB first to try out.

**Comment by ngreenwald** [comment]
Sure, whatever you think is best!

**Comment by willgraf** [comment]
> It would be nice to have an optional comment box for annotators to fill out with suggestions/issues

Like a text form to send an email?

> It would be nice to add label view to "edit" mode

I'm not 100% sure what this means.

> The current color map isn't great, and it's hard to differentiate neighboring cells with similar values.

Seems like we could make this configurable, where users can select their own colormap somewhere. It seems like a good feature.

> It would be nice to change the name from "edit" mode to instead be either pixel edit or label edit

This should be fixed in #154 

> The links to Github and DeepCell at the top of browser caliban don't work.

This should be fixed in #154

**Comment by ngreenwald** [comment]
The comment box is now working. 

Geneva is working on the second one. Basically, there are two ways to view the labels in caliban; either label view (where each cell is colored a different color) or outline mode, where each cell is represented as a white outline. Currently, the first view doesn't exist when editing individual pixels, only when editing whole cells.

**Comment by geneva-miller** [comment]
> > It would be nice to add label view to "edit" mode
> 
> I'm not 100% sure what this means.
> 
I think Noah is referring to the image that's displayed when in pixel-editing mode? Eg, as an alternative to showing the raw image + label outlines, the solid-color labels are displayed and you can modify them with a brush.

> > The current color map isn't great, and it's hard to differentiate neighboring cells with similar values.
> 
> Seems like we could make this configurable, where users can select their own colormap somewhere. It seems like a good feature.
> 
I dream of the day when we can use something like checkboxes instead of keybinds.

**Comment by MekWarrior** [comment]
Closing in response to sunsetting of js version in favor of React.
