### ISSUE TITLE
Caliban Browswer/Figure8 bug report thread

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#151]
We decided to have a single issue where random crashes etc can be reported, with any associated information, from our annotators.

**Comment by ngreenwald** [comment]
1 min+ lag: Christine (not using Chrome) found that it was taking a minute or more for actions to update

**Comment by ngreenwald** [comment]
Page not responding: Issue (on chrome) where labels wouldn't update, then got a message from chrome saying this page is not responding. Tuesday April 14th in afternoon.

**Comment by ngreenwald** [comment]
1 min+ lag: Using Chrome. 

'While annotating the images, the tool gets unresponsive with every action that I take. Every action caused a lag for a few minutes before the page responded again. This lasted for like the first 30-40min of using the tool… I waited it out, and it is now working fine.'

April 21st, 11:10 PM

**Comment by ngreenwald** [comment]
#142 is a subset of these issues, keeping it open for now

**Comment by willgraf** [comment]
> "I got this error a couple times when I'm in the middle of drawing something, and it'll just sit there shaded without turning into an outline. But it seemed to fix itself after a little bit"

Thank you for the details and the screenshot! It looks like the following lines in `render_cell_info` are the culprit:

```javascript
let track = tracks[mode.feature][current_label.toString()];
$('#slices').text(track.slices.toString());
```

`track` is undefined! Is this because of the `504` error jquery hit right before it?

**Comment by ngreenwald** [comment]
April 29 4:00 AM PST

"While I was going through the correction, I faced the same issue as before where the tool would lag for a few minutes every time I used the brush or the eraser. This lasted for the entire duration of the task. I made as much edits as I could and submitted the edited image on the tool page (filename: caliban-input__caliban-output__multiplex__Eliot_Point17__ke_fix__correction__stitched_data.npz), but didn’t manage to submit it on the task page before it timed out"


This was on a 1024x1024 image. The tool is fairly slow on images this big, and takes about 4 seconds to update after each action. However, the above seems like it was much longer than that, and is probably related to the lag issues above.

**Comment by ngreenwald** [comment]
May 10th 1:00 PST:
"Just wanted to let you know that I was only able to annotate half of an image because I faced the lag issue and timed out. "

Looks like the whole page is sometimes timing out?

**Comment by willgraf** [comment]
What specifically happens with the page "timed out"? Is that an HTTP error? Is there anything in the console?

**Comment by ngreenwald** [comment]
Okay, so the 'time-out' was actually just the job expiring, since there's a maximum of 1.5 hrs per job. 

For the lag issue, here's what Ke said: 
"When the tool doesn’t respond, there’s no error message. The page stops responding and I can’t make any edits on the tool until it responds again after 5 minutes or so."

Next time it happens I asked for the console logs.

**Comment by ngreenwald** [comment]
I'm getting this error message when trying to view a very large NPZ. I can view it in desktop caliban without any issues, so I don't think I messed anything up in the formatting, but it can't be ruled out 
![image](https://user-images.githubusercontent.com/13770365/82688683-22783580-9c0e-11ea-81c2-6f40fe95a7ce.png)

**Comment by geneva-miller** [comment]
The database connection will time out on very large files (they take too long to load). @willgraf is the timeout a setting we can (or should) change?

**Comment by ngreenwald** [comment]
I can load a different NPZ of the same size without this issue, something specific to this file

**Comment by ngreenwald** [comment]
[stitched_data.npz.zip](https://github.com/vanvalenlab/caliban/files/4669639/stitched_data.npz.zip)

**Comment by geneva-miller** [comment]
Looks like the link to access it should be https://caliban.deepcell.org/caliban-input__caliban-output__multiplex__20200413_Human_Agreement__Roshan_P101__output__correction__stitched_data.npz?pixel_only=False&label_only=False&rgb=True (there were extra underscores between `output` and `correction`). That said, using the corrected url doesn't work to load the file either (produces a different error, `sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2006, 'MySQL server has gone away')`, which appears to be a timeout issue of some kind)

**Comment by willgraf** [comment]
I think the `(2006, 'MySQL server has gone away')` error could also be caused by too large a payload.

**Comment by ngreenwald** [comment]
I retried it today and it's working fine, no error message

**Comment by ngreenwald** [comment]
Reuploaded the file, so it's possible something was corrupted, or it was somehow related to the url I supplied

**Comment by ngreenwald** [comment]
The annotators running the job last night reported that they were getting frequent time-out issues with caliban.

**Comment by MekWarrior** [comment]
I believe this issue is stale. Closing in response to sunsetting of js version in favor of React.
