### ISSUE TITLE
update canvas for trk files

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#152]
Ideally, would be part of a deeper refactor of shared trk/npz code in browser, to avoid duplicating a bunch of development. Should address #41, #51, #131, and #140 for trk files (these issues are marked as "done" in the data engineering project to reflect that they're no longer bottlenecks for npzs, but they should be implemented across all use cases before being closed).

**Comment by willgraf** [comment]
I believe this is closed by #282 (assuming that #51 is closed by it as well)
