### ISSUE TITLE
handle_draw sends duplicate mouse trace coordinates in payload.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/deepcell-label#158]
`mouse_trace` can contain duplicate mouse coordinates, which are sent over to the backend and never de-duplicated. This means we are sending needlessly large payloads to the backend, and we are using those payloads to do work twice in the backend.

We should both:

1. Remove duplicates in `caliban.py` before looping over the `trace` object. This can be done by converting each sub-array to a tuple and wrapping in a set, like `unique_trace = set([tuple(t) for t in trace])`.

2. Prevent the frontend JS from sending over duplicate values in the first place. This is a little tricky, as in JS `[1] !== [1]`. Maybe we can institute a new class `Coordinate`, and use that as a comparison instead of the arrays. Then we can cast back to an array in `handle_draw`. Here's a [StackOverflow post](https://stackoverflow.com/questions/14415787/remove-duplicate-element-pairs-from-multidimensional-array) that discusses some of the difficulty.

**Comment by geneva-miller** [comment]
Not actually closed by #196, although it should be more straightforward to modify mouse trace behavior (now `state.trace`) to prevent it from adding duplicate coordinates.
