### ISSUE TITLE
Look into compressed npzs

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#169]
Using `numpy.savez_compressed` will result in smaller file sizes than `numpy.savez`, which is currently what we use to create our npz files. We should look into using compressed npzs, which would need to be compatible with both caliban and the data pipeline.

**Comment by willgraf** [comment]
AFAIK `savez_compressed` is strictly better and should be used in place of `savez` everywhere.

**Comment by ngreenwald** [comment]
Yes, I've started using it locally over the last month, it's great.

**Comment by calboi91** [comment]
Will the compressed npz be used for .trk files as well? I think .trk files currently contain uncompressed npy array files.
