### ISSUE TITLE
Browser caliban can't handle (large?) floats in channel data

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#171]
I tracked down the issue with the NPZs not loading, it looks like it was due to the dtype of the X data. My guess is the combination of a 1024x1024x image and the fact that the data was float64 lead to a memory error, but I'm not 100% sure. 

Here's a 1024x1024 image, int16, that loads fine: https://caliban.deepcell.org/caliban-input__caliban-output__multiplex__20200413_Human_Agreement__Roshan_P101__output__correction_int__stitched_data_int.npz?pixel_only=False&label_only=False&rgb=True

Here's the same 1024x1024 image, but with float64, that fails to load: 

https://caliban.deepcell.org/caliban-input__caliban-output__multiplex__20200413_Human_Agreement__Roshan_P101__output____correction__stitched_data.npz?pixel_only=False&label_only=False&rgb=True

Please don't modify the data in the first link, it's currently being worked on for the human comparison analysis.

**Comment by willgraf** [comment]
The error I got in my console via the second link:

```
Uncaught TypeError: CanvasRenderingContext2D.getImageData: Argument 3 is not a finite floating-point value.
```
