### ISSUE TITLE
optionally hide labels in pixel-editing mode

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#173]
Useful viewing option if annotators are restricted to non-rgb pixel-only mode. Specifically helps with looking at edges of cells. Probably just "L" keybind for now in non-rgb mode (I don't think there's a need for this for rgb browser mode?) and could add a checkbox in the future if we figure out an appropriate place to put it. Would be nice to eventually have this be an annotation opacity slider instead of a binary toggle.

**Comment by MekWarrior** [comment]
I believe this issue is stale. Closing in response to sunsetting of js version in favor of React.
