### ISSUE TITLE
Incrementally trim/add pixels to label

### ISSUE THREAD

**Issue by ccamacho89** [vanvalenlab/deepcell-label#175]
Would be useful to have feature added that allows user to trim or add pixels to edge of a label, in one pixel increments, in either dilate or erode.

**Comment by geneva-miller** [comment]
Yes, I think that's a great idea and should be pretty easy to implement. I'm thinking about what keybinds/user interaction would be most appropriate to trigger this type of label modification.

In the case where the expansion of a label conflicts with another, existing label, would your preference be to draw over the existing label, or to not expand in regions where there's a conflict?

**Comment by geneva-miller** [comment]
There's a few keybind options here:
- Y to trigger choice between erosion OR dilation, confirmation key decides which one
    - I currently have this set up for "X to erode, space to dilate" but I'm not sold on it, I'm wary of accidentally triggering label deletion when it's not wanted. T to erode and Y to dilate?
- Y triggers either erosion or dilation, and another keybind triggers the other option

Aside from thinking about keybinds I do have the functionality in place, sorry for the delay. Let me know what you think about the keybinds and I will push the changes pretty soon.

**Comment by ccamacho89** [comment]
I think T to erode and Y to dilate would be great. I have the same concerns
as you about accidentally triggering label deletion when unwanted. In the
cases where the label is already one pixel and the user selects erode,
would the label be deleted, would user receive an error message, or would
nothing occur?

**Comment by geneva-miller** [comment]
My current implementation is that a single pixel being eroded would remove that label from the image. It could be changed so that the label remains untouched if erosion would otherwise delete the label.

**Comment by ngreenwald** [comment]
I don't think there's any scenario where we'd want to keep a label that's only a single pixel

**Comment by tddough98** [comment]
Closed by #218
