### ISSUE TITLE
How to preprocess annotated image stacks from ImageJ/TrackMate into .npz

### ISSUE THREAD

**Issue by emmachancellor** [vanvalenlab/deepcell-label#227]
Hi there, I'm a student researcher at the University of Chicago working on single cell analysis for cancer research and I am hoping to use DeepCell to track cells. My lab already has a lot of annotated movies that were annotated using TrackMate in ImageJ and we would like to use this as training data for DeepCell. However, I'm struggling to correctly format our data into the compressed .npz files. 

Our data is currently stored as large (~1.6GB) .tif image hyper stacks that were annotated in TrackMate, and while I understand how to compress the .tif files, I'm not sure what needs to be contained in the annotation data and how this should be formatted for DeepCell. When I have investigated the DeepCell Label test.npz files, I see that there are two arrays, one as a "raw" array and one as an "annotated" array. What information is stored in these arrays and what format should data be in prior to compressing to a .npz? 

The TrackMate annotation software from ImageJ provides an XML file of track statistics, but it also contains a lot of information that I do not believe is necessary for DeepCell. For example, here are the column headers for the XML file that TrackMate creates for the track statistics after annotation: 

Label | ID | TRACK_ID | QUALITY | POSITION_X | POSITION_Y | POSITION_Z | POSITION_T | FRAME | RADIUS | VISIBILITY | CELL_DIVISION_TIME | MEAN_INTENSITY01 | MEAN_INTENSITY02 | MEAN_INTENSITY03 | MEAN_INTENSITY04 | MEAN_INTENSITY05 | MEAN_INTENSITY06 | MEAN_INTENSITY07 | MEAN_INTENSITY08 | MEAN_INTENSITY09 | MEAN_INTENSITY10 | MANUAL_COLOR | MEAN_INTENSITY | MEDIAN_INTENSITY | MIN_INTENSITY | MAX_INTENSITY | TOTAL_INTENSITY | STANDARD_DEVIATION | ESTIMATED_DIAMETER | CONTRAST | SNR

What information from the TrackMate annotation statistics should I use to make the annotation array needed to create a training dataset for DeepCell and how can I get the data that I have into the correct format to run DeepCell? Do you have any examples or know of any other researchers that have used TrackMate to annotated data and then use this in DeepCell? Thank you very much for your help. If there is a better medium to communicate about these issues, feel free to email me at ecdyer@uchicago.edu.

**Comment by tddough98** [comment]
Hi Emma,

You'll want to load your raw images and segmentations into numpy, and then use [numpy.savez](https://numpy.org/doc/stable/reference/generated/numpy.savez.html) to create .npz file containing multiple arrays 
The .npz file should contains two arrays:

- an X array containing raw images with shape (frames, height, width, channels)
- an y array containing segmentations with shape (frames, height, width, features) [usually features = 1 unless your segmenting multiple classes like nuclear + cytoplasm]

The y array should have a unique positive number for each segmented object. Every pixel where that object is present in the raw X array should have that integer at that pixel in the y array. The same object should have the same label between frames. For example, if you had a single object same object taking up the entire image in every frame, then your y array would contain all ones. 

It seems like TrackMate does do segmentation, but I'm not sure if it has pixel level information as needed to create a segmentation array. Some of the fields you listed like POSITION_X | POSITION_Y | POSITION_Z | POSITION_T | FRAME | RADIUS seem like they define a circle around the tracked object. You could try to convert these to a segmentation array by assigning all the pixels within that circle the label ID, using something like [skimage.draw.circle](https://scikit-image.org/docs/dev/api/skimage.draw.html#skimage.draw.circle).

If you want to use your data to train specifically a tracking model with DeepCell, you will need to further create .trk files, which is a custom file format. A .trk file is a tarball containing the raw array as `raw.npz`, the segmentation array as `tracked.npy`, and a lineage file named `lineage.json`. The lineage file contains an object for each tracked cell and records the frames the cell is present in, when the cell divides, its parent, and its daughters. I don't see that information in the fields you listed above, but it looks like TrackMate does build lineages with parent-daughter relationships, so you should have the information you need. I can provide more details on how to build the `lineage.json` file if you're reaching that.


To get some concrete examples, here are an [example .npz file](s3://caliban-input/test/test.npz) and an [example .trk file](s3://caliban-input/test/RAW264_S0_Batch02.trk). You can unzip the .trk file, and it should unzip to a folder containing three files: `raw.npy`, `tracked.npy`, and `lineage.json`.

Lastly, DeepCell Label can help you view and edit your annotated movies, but if you already have annotated movies and don't need to expand/improve your dataset, you may want to look into [deepcell-tracking](https://github.com/vanvalenlab/deepcell-tracking) or [deepcell-tf](https://github.com/vanvalenlab/deepcell-tf) for model training from an existing dataset.

**Comment by emmachancellor** [comment]
Thank you so much for this information, it is immensely helpful! I will follow your directions and suggestions for how to create the segmentation array.

**Comment by willgraf** [comment]
Closing this as it seems the question was answered. Feel free to re-open if this warrants more discussion.
