### ISSUE TITLE
Label database filling up from large action history

### ISSUE THREAD

**Issue by tddough98** [vanvalenlab/deepcell-label#230]
Over the weekend, our database on AWS reached its storage capacity, so we could not create new projects from being created and update existing projects. @willgraf and I bumped up the storage capacity by 100 GB as a stopgap while we made moves to back up the database and clear the way to free space. However, the underlying issue of large storage is not resolved, and we need to work out our requirements for the Label action history dataset.

Here are a couple possible approaches and their tradeoffs:

| Approach      | Pros | Cons |
| ----------- | ----------- | ------ |
| Create a larger database      | Easiest <br />  Keeps dataset in one place  | Cost grows over time |
| backup and flush periodically (when full/monthly)   | Frees the most space in RDS <br /> Could store backups offline  | Breaks up dataset across backups |
| Flush out action history blobs when submitting file  | Easier  | Lose action history for finished files |
| Flush out blobs when submitting &  develop lightweight action history (like actions & arguments) for finished files  | Can reconstruct action history without blobs   | Development time <br /> Schema changes/Existing projects won't have this lightweight history <br/> Actions may depend on Label version |

**Comment by geneva-miller** [comment]
IMO periodic backups that move blobs off of RDS to offline storage also have the downside of increasing storage requirements over time. Consider annotation jobs "from scratch"--each label must be added in, often over the course of a few actions (a couple of brush strokes, a "fill" action, and maybe a touchup). A cytoplasm job with 10,000 objects could feasibly have 40,000 associated frames in the action history.

**Comment by willgraf** [comment]
This will be largely resolved by converting the PickleType columns to compressed NPZ data.

#238 is the first step in a schema migration towards fixing this. There will also be one more PR completing the migration and using compressed NPZ for all fields. Once that second PR is in, this issue can be considered closed.

**Comment by willgraf** [comment]
I believe this issue was fixed by #242.

Please re-open if I am mistaken.
