### ISSUE TITLE
sqlalchemy 1.4.0 release breaks flask-sqlalchemy

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#232]
**Describe the bug**
The latest sqlalchemy release breaks flask-sqlalchemy. Our crowdsource deployment website is down as a result.

**To Reproduce**
Try to access a file via caliban.deepcell.org (not label.deepcell.org--this still works fine)

**Screenshots**
![image](https://user-images.githubusercontent.com/45578681/111278890-52f2eb00-85f7-11eb-8f71-6b6d9e718d59.png)

**Additional context**
Limiting the sqlalchemy version in `browser/requirements.txt` (`sqlalchemy<1.4`) should be enough to fix it. I'm not sure what the appropriate db configuration settings are at this point, so I have not been able to redeploy a working version.

**Comment by geneva-miller** [comment]
More info:

The specific error in the logs
![image](https://user-images.githubusercontent.com/45578681/111354721-d76b5b00-8643-11eb-8e34-50f972de6d49.png)

Relevant [stackoverflow post](https://stackoverflow.com/questions/65610809/retrieving-data-from-rds-gives-attributeerror-sqlalchemy-cimmutabledict-immuta) and [issue on the flask-sqlalchemy repo](https://github.com/pallets/flask-sqlalchemy/issues/885). Although this has been a known issue for several months, version 1.4 was not automatically installed before now because it was in beta.

**Comment by willgraf** [comment]
Do we use the `immutabledict` object in our models?

I'm happy with just pinning to < 1.4.0, but it would be good to know where we will need to make changes in order to upgrade in the future.

**Comment by willgraf** [comment]
#234 added `sqlalchemy<1.4` to `requirements.txt`, fixing this issue.

It looks like `flask-sqlalchemy==2.5.1` should also fix this issue?

**Comment by tddough98** [comment]
Closed by #234 (for sqlalchemy version) and #287 (for flask-sqlalchemy version)
