### ISSUE TITLE
Have trouble on installation

### ISSUE THREAD

**Issue by jizhouh** [vanvalenlab/deepcell-label#237]
Hello, please forgive me if I post this question at wrong place.

I followed the instruction, and after running application.py I could open the site. However I could not interact with the site. The submit button and dropzone were not activated. I saw "GET /static/js/index.js HTTP/1.1" 404 in the shell, so I copied "index.js" from src to /static/js (I manually created a directory named js). Then the message disappeared, but the problem was still there. 

Thanks for helping me.

**Comment by tddough98** [comment]
Hello! This is definitely the right place to post issues like this, thank you for posting. We've been updating our project structure and build process recently, so some of our documentation on getting started is a bit out of sync. We'll work on getting that up to date soon, but let me outline the full set up process here.

- clone the repository with `git clone https://github.com/vanvalenlab/deepcell-label.git`
- open the repository with `cd deepcell-label`
- (optional) set up a virtual environment to set up dependencies, either with  [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) or with [conda](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment)
  - for venv, use `python3 -m venv deepcell-label` then `source deepcell-label/bin/activate`
  - for conda, use `conda create --name deepcell-label` then `conda activate deepcell-label`
- install python dependencies with `pip install -r requirements.txt`
- install javascript dependencies with `npm install`
- build the static javascript files with `npm run build` 
  - __this is the issue you were running into.__ The repository has the source javascript files in `src/` but we need to build the compiled javascript into the `static/js` folder.
- start the flask server with `export FLASK_APP=application.py` and then `flask run`

You should now be able to use the app on `localhost:5000` in your browser. Good luck and let us know if you have any further issues!

**Comment by jizhouh** [comment]
> Hello! This is definitely the right place to post issues like this, thank you for posting. We've been updating our project structure and build process recently, so some of our documentation on getting started is a bit out of sync. We'll work on getting that up to date soon, but let me outline the full set up process here.
> 
>     * clone the repository with `git clone https://github.com/vanvalenlab/deepcell-label.git`
> 
>     * open the repository with `cd deepcell-label`
> 
>     * (optional) set up a virtual environment to set up dependencies, either with  [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) or with [conda](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment)
>       
>       * for venv, use `python3 -m venv deepcell-label` then `source deepcell-label/bin/activate`
>       * for conda, use `conda create --name deepcell-label` then `conda activate deepcell-label`
> 
>     * install python dependencies with `pip install -r requirements.txt`
> 
>     * install javascript dependencies with `npm install`
> 
>     * build the static javascript files with `npm run build`
>       
>       * **this is the issue you were running into.** The repository has the source javascript files in `src/` but we need to build the compiled javascript into the `static/js` folder.
> 
>     * start the flask server with `export FLASK_APP=application.py` and then `flask run`
> 
> 
> You should now be able to use the app on `localhost:5000` in your browser. Good luck and let us know if you have any further issues!

It works, thanks a lot!

**Comment by mezwick** [comment]
Hi,

I have tried to follow the above instructions for install via a conda environment. However, return the following error when at the 
`pip install -r requirements.txt` stage.

```
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\MS\Anaconda3\envs\deepcell-label\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WinAdm\\AppData\\Local\\Temp\\pip-install-f08er4ty\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\WinAdm\\AppData\\Local\\Temp\\pip-install-f08er4ty\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\WinAdm\AppData\Local\Temp\pip-pip-egg-info-2ecnvlx4'
         cwd: C:\Users\WinAdm\AppData\Local\Temp\pip-install-f08er4ty\matplotlib\
    Complete output (47 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.8.5 (default, Sep  3 2020, 21:29:08) [MSC
                            v.1916 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.20.2]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: yes [installing]

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

One thing was, i did install pip into the environment with `conda install -c anaconda pip`, after creating the `deepcell-label` conda environment as above. 

I have `conda 4.10.1` and `pip 20.2.4` installed.

**Comment by mezwick** [comment]
Solved some of my local windows conda installation issues by running 

1. `conda create --name deepcell-label` 
2. `conda activate deepcell-label`
3. **`conda install matplotlib=3.0.3`**
4. `pip install -r requirements.txt`

For the javascript side of things, i can then get as far as npm install, but also need to run
5. **`conda install -c conda-forge nodejs`**
6.  `npm install`
7. `npm run build`

Then as i am running windows powershell i have  run 
8.  $env:FLASK_APP = "application.py"
9. flask run

However at this point i return an operational error >.<

...think i better look to run on a linux virtual environment at this point

**Comment by willgraf** [comment]
Apologies for letting this get so stale! 

My first guess regarding the `OperationalError` is that you do not have the environment variable `SQLALCHEMY_DATABASE_URI` set. SQLAlchemy uses this as a database string to connect to the database.

**Comment by willgraf** [comment]
I'm going to close this issue due to inactivity. If you are still having issues please re-open it.
