### ISSUE TITLE
Include a link to the GitHub in the Footer

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/deepcell-label#244]
We could include a link to the GitHub issues page in the footer of the page (much like on deepcell.org). Since we expect some new users to use the Visualizer, a link to the GitHub issues page could help funnel any issues or feature requests to the right place.

**Comment by tddough98** [comment]
The viewer #243 now has an updated footer that links to the issues page, which captures the most public facing part of Label right now. Once we release DeepCell Label 0.2 with a full React-based architecture, we'll merge this into the master branch.
