### ISSUE TITLE
DCL React prototype doesn't allow new edits

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#246]
**Describe the bug**
After interacting with some number (5?) of object segmentations, the brush stops being able to draw new cells. 

**To Reproduce**
It happened twice, so I'm not sure exactly what is required to reproduce. I was demoing the software, and successfully edited a few different cells, deleting, brushing, etc. However, I then could no longer add new cells with the 'N' key. I was able to draw with the brush, but after releasing the brush stroke, the new cell never appeared.

**Comment by ngreenwald** [comment]
Tom and I both can't reproduce the error. I believe his suspicion is correct, this was probably because I was in conversion brush mode, not in draw mode.

**Comment by tddough98** [comment]
Here is the conversation we had in slack

> One thing that may be happening is that some other label is selected as the background, so the brush only overwrites that other label instead of drawing the new label onto unlabeled areas
> the selected labeled widget at the bottom of the toolbar shows whether the foreground/background is selected as a label/no label
> Pressing escape makes the background label "no label" again, so you can draw the new label over unlabeled areas.
> right now, we color the brush outline red when the foreground is "no label" & the background is some other label, or when we are erasing a label.
> Maybe we should also color the brush outline red when using the "conversion brush" so it's clear that drawing on unlabeled areas won't do anything


> Let me see if I can reproduce it again
> I thought I had pressed escape, but maybe I didn’t
> If this doesn’t come back again, I would assume that’s what was happening, the conversion setting was on
> Agreed re: having red when background label is a cell rather than background

Takeaway: color the brush outline red in conversion mode to make it obvious that painting unlabeled areas won't work
