### ISSUE TITLE
Submit button fails when output bucket is specified in project url

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/deepcell-label#258]
When we specify an output bucket in a project url, e.g. `?projectId=xxxxxxx&bucket=some-bucket` the submit button fails save data to the output bucket. This is occurring at the this deployment: [https://d3g94azckse7wo.cloudfront.net](https://d3g94azckse7wo.cloudfront.net).

@geneva-miller investigated what was happening and linked it to this line:
https://github.com/vanvalenlab/deepcell-label/blob/f307263f12dbd9ab7aed36674f531cc09c373b66/visualizer/src/service/service.js#L7
and suggested that it be changed to: `const bucket = search.has('bucket') ? search.get('bucket') : 'caliban-output';`

**Comment by tddough98** [comment]
This is fixed and redeployed with the change Geneva suggested. A hard refresh (Ctrl + F5 on Windows or Command + R on Mac) will make sure that the latest assets are fetched with this bug fix
