### ISSUE TITLE
Prototype browser for data registry

### ISSUE THREAD

**Issue by tddough98** [vanvalenlab/deepcell-label#267]
Currently viewing files in the data registry can be slow and manual as it requires custom notebooks. If we can use Label to read files from the registry and view them, then we could speed up file review for the registry. 

As a prototype, I suggest a local deployment with a feature flag to read data from a folder instead of our current database and adding two fields to the `.env` file

- a flag to read data from a folder instead of from the database, and
- which folder to read from.

The read from folder flag needs to change the behavior of routes that serve data and recreate the functionality from `models.py` used to create this data. For these routes, we will need to overload `projectId` to use a filename instead of the 12 characters IDs used in the database.

Here are the routes to be modified with the feature flag and the `models.py` functionality they currently use

- `/api/project/<projectId>`: `make_first_payload()` to get project level attributes like height, width, etc.
- `/api/raw/<projectId>/<channel>/<frame>`: `get_raw_png` to create an image from the raw data
- `/api/labeled/<projectId>/<feature>/<frame>`: `get_labeled_png` to create an image from the labeled data
- `/api/array/`: `get_labeled_array` to create the array of labels with outlines
- `/api/semantic-labels/`: accesses `project.labels.cell_info[feature]` to get the semantic labels for that feature
- `/api/colormap/`: `get_max_label(feature)` to find the highest label for that feature
s

**Comment by tddough98** [comment]
There are three branches with some work on 

* https://github.com/vanvalenlab/deepcell-label/tree/registry-viewer
* https://github.com/vanvalenlab/deepcell-label/tree/registry-viewer-with-tracking
* https://github.com/vanvalenlab/deepcell-label/tree/mrgn/registry-viewer

These branches are out of date as of the 0.4 release, so we should re-evaluate the needs for a register viewer and recover or delete these branches as needed.

**Comment by ykevu** [comment]
This issue is now being worked on as a separate project.
