### ISSUE TITLE
Label number goes to NaN

### ISSUE THREAD

**Issue by GMaciag** [vanvalenlab/deepcell-label#280]
**Describe the bug**
Cannot add more than one label when annotating your own image in label.deepcell.org 
The label number after "1" goes to NaN. The Palette keeps showing NaN, you cannot switch between annotations, you cannot add new ones. The NaN annotation ends up hidden "under" the image (increase opacity to see).

**To Reproduce**
1. Go to [label.deepcell.org ](url).
2. Load your own image.
3. You can annotate the first cell, it will be labelled "1" as expected. 
3. Press 'n' (or select the plus sign in the Foreground/Background Palette).
4. The cell number is now NaN.

**Expected behavior**
You should be able to create multiple cell annotations.

**Screenshots**

<img width="1665" alt="Screenshot 2021-11-26 at 13 58 17" src="https://user-images.githubusercontent.com/31366577/143585051-30a3da17-7c9c-4e64-bb22-5bcde556f1d2.png">

**Additional context**
The issue does not occur when working on an example dataset included in the website.

**Comment by tddough98** [comment]
[label.deepcell.org](label.deepcell.org) has now been fixed so you should be able to add new labels to any file now. Thank you for raising this issue and please let us know if you have any other issues or questions come up!
