### ISSUE TITLE
Unable to run flask 

### ISSUE THREAD

**Issue by StephanDrothler** [vanvalenlab/deepcell-label#284]
Seemingly, I successfully installed the requirements.txt in my virtual environment (I changed 
pillow>=7.1.0,<8.3.2 to pillow==8.3.2, otherwise a had an unresolvable version conflict).
Subsequently, I executed "flask run" and the following error message popped up:

"*Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
*Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" pr "app.py" module was not found in the current directory."

How do I set the correct environment variable and provide the right modules?

**Comment by tddough98** [comment]
We've an included an example `.env` file in the repo named `.env.example` that has the FLASK_APP environment variable prepopulated. If you remove the `.example` suffix from that file so the name is just `.env`, then those environment variables will be used by the app. We use the `.example` suffix to avoid accidentally commiting the real `.env` to the project, as it often contains sensitive environment variables like access keys or database passwords.

You can also set the environment variable without using a `.env` file by running the command
```bash
export FLASK_APP=application
```
Here's a [blog post](https://opensource.com/article/19/8/what-are-environment-variables) about environment variables with some more context and tips.

I'll add to the README instructions to make an `.env` file from `.env.example` and then close this issue. Thank you for posting this, we appreciate everything that can make the project more accessible and useful! Let me know if you have any other questions or issues and I'll be glad to help out.
