### ISSUE TITLE
Error in setting up the client side

### ISSUE THREAD

**Issue by aysanaghazadeh** [vanvalenlab/deepcell-label#329]
To setup the client side I went through the readme file; however, I got this error:
Command: node-pre-gyp install --fallback-to-build on canvas failed.

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/DeepCell/deepcell-label/visualizer/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/usr/local/bin/node" "DeepCell/deepcell-label/visualizer/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd DeepCell/deepcell-label/visualizer/node_modules/canvas
gyp ERR! node -v v18.2.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node DeepCell/deepcell-label/visualizer/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/DeepCell/deepcell-label/visualizer/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "DeepCell/deepcell-label/visualizer/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /DeepCell/deepcell-label/visualizer/node_modules/canvas
node-pre-gyp ERR! node -v v18.2.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
Failed to execute 'DeepCell/deepcell-label/visualizer/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release/

I would appreciate it if you could help me with this issue.

**Comment by tddough98** [comment]
It looks like this is related to node 18 support: https://github.com/Automattic/node-canvas/issues/2025

You can switch between node versions with nvm (Node version manager): https://github.com/nvm-sh/nvm. We use node 16 for our testing and development. If you switch to node 16 and the issue persists, please let us know
