### ISSUE TITLE
Add cell type labels

### ISSUE THREAD

**Issue by tddough98** [vanvalenlab/deepcell-label#340]
Last summer, @geneva-miller and I prototyped cell types labels in DeepCell Label. Our process was documented in these issues

- #251 
- #252 
- #253 
- #254
- #255

and there is code from those efforts in on the branch [cell-types](https://github.com/vanvalenlab/deepcell-label/tree/cell-types), but the code is far out sync with the 0.4 release as it's over a year old.

The 0.4 release supports additional label types (spots, divisions, cells), so refitting the cell types work from these issues and branch would fit in with the recent improvements.

**Suggested approach**

To add a new label type,
- loading the labels when creating a project
- add an event bus for the label type
- add a state machine to store and edit the labels 
  - broadcast changes on the event bus
  - listen to  event buses for dependent labels to update when
- add a state machine to manage the UI & send events to edit the labels
- track the state machines in the undo/redo history
- persist the labels in IndexedDB by listening to the event bus
- add a Canvas component to display the labels
- add a Controls component to edit the labels
This can serve as a template for adding any new label type.

Here are specific tasks on what files to change and create for cell type labels:
- add `load_cell_types` and `write_cell_types` functions to the Loader class in `loaders.py`
- add a cellTypes event bus in `projectMachine`
- add a `cellTypesMachine` to store and edit the cell types
  - spawn it as a child of `projectMachine`
  - send a REGISTER_LABELS event to the undo machine
  - send a CELL_TYPES event containing the labels to the cellTypes event bus
  - listen to the cells event bus to stay in sync with cells from CELLS events
- add a `CellTypesCanvas` component to `Canvas` to display the cell types labels
- add a `CellTypeControls` component that provides a UI to edit the cell types labels
- add a `editCellTypesMachine` to interpret interactions with the `CellTypeControls` and send events to `cellTypesMachine`
  - spawn it as a child of `editMachine`
  - send a REGISTER_UI event to the undo machine
- listen to the cellTypes event bus in idb machine to receive and write the cell types labels to the database

**Comment by tddough98** [comment]
There is a branch [cell-types](https://github.com/vanvalenlab/deepcell-label/tree/cell-types) with the initial efforts for issues 251-255 from last summer. The code is out of date with the current project, but some of the ideas and UI snippets could be useful. Please delete this branch as soon as further work is started on cell types.

**Comment by ykevu** [comment]
Cell types have now been implemented with the latest merges.
