### ISSUE TITLE
Add c to cell labels

### ISSUE THREAD

**Issue by tddough98** [vanvalenlab/deepcell-label#347]
Cells labels are currently shared across segmentation channels. For example in mesmer, value in the nuclear segmentation encodes the same cell as a value in the whole cell segmentation.

The segment editing API only sees one segmentation channel at a time, so it can inadvertently delete cells in the other segmentation channel if they are not present in the current channel. This happens when editing our first example file "2D tissue segmentation" on the DeepCell Label homepage.

To add channels to the cell labels, we should
* generate cell labels from each segmentation channel separately in loaders.py
* send the cells for the current channel in segmentApiMachine.js
* recombine the cells for the edited channel
* add functions to get the cells for the current channel in Cell.ts
* filter by both c and t when updating the edited cells from the segment API in cellsMachine.js (see the updateCells action)
* (optional) add channel modes in addition to the one/future/past/all time modes shown in the Cells tab to edit cells across channels

**Comment by ykevu** [comment]
Hi Tom, are there still any parts of this issue that need to be addressed?

**Comment by tddough98** [comment]
This can be closed. The last optional bullet I think is not in there, but that's an extra feature and there can be a new issue to request it if needed. I still have notifications on for issues, but try to tag me by username @tddough98 to make sure I get a notification
