### ISSUE TITLE
Some labels do not render on canvas but show up in the Selected/Hovering area 

### ISSUE THREAD

**Issue by ellenemerson** [vanvalenlab/deepcell-label#362]
**Describe the bug**
Some labels do not render on the canvas even though they still show up in the Selected/Hovering area when selected or hovering over the area with the cursor.

**To Reproduce**

1. Upload either of the files attached to this issue to DeepCell Label.
2. View either cell 14 or cell 7 throughout all frames.
3. Hover/select either cell to observe that the cells are present but not rendered on the canvas throughout all frames.

**Expected behavior**
Labels that show up when selecting/hovering should be rendered on the canvas.

**Screenshots**

Cell 14 is the cell in the center of the frame with apparently no label.
![Screen Shot 2022-07-29 at 11 46 29 AM](https://user-images.githubusercontent.com/7650753/181824864-bf4989b2-0636-4155-8bd5-3b9e8f4305a1.png)

**Desktop (please complete the following information):**

Using the browser version at label.deepcell.org on Google Chrome on macOS Monterey 12.4.

**Additional context**
I have attached a .zip file containing two files that exhibit this behavior: [deepcell-label-issue.zip](https://github.com/vanvalenlab/deepcell-label/files/9222518/deepcell-label-issue.zip)
1. 20220506_ep_conc_test003xy1c1_04.trk: This file is uncorrected output of the IOU tracking algorithm. Cell 14 is present in frames 1-30, but only visible on the canvas in frames 1-7.  In frames 8-30, its presence only shows in the Selected/Hovering area.  Similarly cell 7 is in frames 0-30 but only visible on the canvas in frame 1.
2. 20220506_ep_conc_test003xy1c1_04.zip: This file is the output of correcting the previous file in DeepCell Label.  Cell 14 is present in frames 0-30 but never visible on the canvas, only in the Selected/Hovering area.  Cell 7 is present in frames 0-30 but only visible on the canvas in frame 1.

**Comment by ykevu** [comment]
Hi Ellen, do you have a link to the edit job you were working on? I wasn't able to reproduce the bug with your files.

**Comment by ellenemerson** [comment]
Sure, I just created a couple projects from the files in this issue and am still seeing the same behavior.  And FYI, I also tried these links on Firefox and Safari as well as Chrome - same behavior on all three browsers.

Here is one for 20220506_ep_conc_test003xy1c1_04.trk: https://label.deepcell.org/project?projectId=JEer_0FNmjoJ&download=true 

And here is one for 20220506_ep_conc_test003xy1c1_04.zip: https://label.deepcell.org/project?projectId=NqVzVou-R_6l&download=true

**Comment by ykevu** [comment]
Unfortunately, I wasn't able to find someone that sees the same issue with either of your links. Can you let me know if you see the behavior on this link?
https://label.deepcell.org/project?projectId=DqYtO5eGlCxW&download=true

**Comment by ellenemerson** [comment]
Yes, I do still see the same behavior.  Strange that it doesn't have the same problem on other machines.  Maybe it's an issue with how browsers render on M1 chip/Apple Silicon?

I attached a video that shows what the behavior I'm referencing so you can at least see what I'm talking about. 

https://user-images.githubusercontent.com/7650753/186534300-aac4c781-e32b-499d-898e-ea5876f50c1c.mov
