### ISSUE TITLE
Not all segmented cells displayed in viewer

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#366]
**Describe the bug**
After segmenting an image with Mesmer, when I clicked "View Results", only a subset of the segmented cells are displayed. 
[combined.tiff.zip](https://github.com/vanvalenlab/deepcell-label/files/9375539/combined.tiff.zip)

**Expected behavior**
All segmented cells should show up. Since the missing cells are all on the bottom, there's probably a maximum number of cells that can be displayed in a single image, and this value is hardcoded too low for dense tissue images. 

**Screenshots**
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/13770365/185442333-bd0fbe39-b696-4d88-a479-69baf8362f0d.png">

**Additional context**
I attached the image I used to make the prediction to the issue. Here's the URL: https://label.deepcell.org/project?projectId=aJS695DpYT7n&download=true

**Comment by ykevu** [comment]
Hi Noah, I was able to find the parameter that results in only 999 of the cells in that file rendering on the canvas (the rendering kernel has a maximum loop iteration count of 1000). My background is not really in biology, so what would you consider a better upper limit? Do you think it reasonable to assume that an image would never need to render over 5000 cells?

**Comment by ngreenwald** [comment]
Yes, I would say 5000 is a good conservative estimate, at least for as long as the max image size remains 2048. Once that gets larger then the number of cells could increase as well
