### ISSUE TITLE
Segmentation changes are lost after browser refresh

### ISSUE THREAD

**Issue by elorapradhan** [vanvalenlab/deepcell-label#370]
**Description of the bug**
Changes made to an image using any tools on the SEGMENT tab (brush, flood, erase, trim, threshold, watershed, autofit, shrink, grow) are lost upon refreshing the page. 

**Expected behavior**
Refreshing the page should preserve all changes made to the image. 

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Version 10.15.6

**Comment by msschwartz21** [comment]
Just seconding that I have seen the same behavior.
