### ISSUE TITLE
Changes to file export to match lab conventions

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/deepcell-label#373]
The current file export makes some choices that do not match lab conventions for how we store our data. In order to simplify the process of retrieving files from DCL jobs, I would like to slightly change the export to match our conventions.

1. Change shape of the axes. Current export axis order is `CZYX` which should be changed to `ZYXC`.
	https://github.com/vanvalenlab/deepcell-label/blob/f374ffadfee40d12eb931e11dc14075c6f6eb152/backend/deepcell_label/export.py#L91
	https://github.com/vanvalenlab/deepcell-label/blob/f374ffadfee40d12eb931e11dc14075c6f6eb152/backend/deepcell_label/export.py#L103
This should be a straightforward change but we should test loading some of the exported images in Fiji and a notebook to confirm that the export is reasonable.
2. Raw data (X) should not be permanently rescaled to 0-255. Currently the data loader saves a new ome.tiff after loading from the original file format.
https://github.com/vanvalenlab/deepcell-label/blob/f374ffadfee40d12eb931e11dc14075c6f6eb152/backend/deepcell_label/loaders.py#L82-L84
Ultimately we do not want to change the dynamic range and dtype of our raw data. I would like to change these lines to eliminate the rescaling. However it may introduce downstream issues with displaying the data, so we can discuss further as those potential issues are discovered.

**Comment by msschwartz21** [comment]
I spent some time looking in the ome.tiff and ome.xml specifications to try to find an explicit constraint on dimension order. Unfortunately the documentation included below really doesn't help. It implies that dimension order should always start with `XY` even though Tom's original specification of `CZYX` clearly seemed to work.

http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html

<img width="958" alt="Screen Shot 2022-09-02 at 2 15 32 PM" src="https://user-images.githubusercontent.com/20373588/188213916-6acee6ed-5839-4de7-b3ce-685f5967a1cf.png">

**Comment by ykevu** [comment]
I saw this as well, but every library I tried has enforced that 'YX' be the last two dimensions, so I think there's some sort of reversal at play. The documentation is usually non-existent or unclear as well. The 'axes' field that Tom used for tifffile has the following description:

![image](https://user-images.githubusercontent.com/55016297/188215703-c9062de9-b444-439a-a2e5-8462e7ef1f69.png)
