### ISSUE TITLE
Local backend deployment without AWS storage?

### ISSUE THREAD

**Issue by kim-fehl** [vanvalenlab/deepcell-label#386]
**Describe the bug**
It seems that with the latest code it is impossible to use the backend fully locally without an AWS storage connection, as possible with version 0.3.0.

**To Reproduce**
1. Build and run the Docker backend container locally as described in manual
2. Open frontend, try to upload npz file in the browser

**Expected behavior**
Frontend interface opens

**Screenshots**
![image](https://user-images.githubusercontent.com/25846538/195343863-a52615c8-f19b-41d5-99e7-935408142eef.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Version 0.4.0 + latest commits @ 2022-10-12
- Python Version 3.9

**Comment by ykevu** [comment]
@tddough98 @msschwartz21 Is this behavior intended? So far as I've been working on DCL an AWS key / S3 bucket has been required.

**Comment by albert180** [comment]
I've got the same problem with a local installation without docker...

**Comment by ykevu** [comment]
As of the 0.4 release there are no plans for working towards supporting fully local deployment, apologies.
