### ISSUE TITLE
Update readme with corrected docker instructions

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#47]
Volume mounted should be $PWD/desktop not $PWD/caliban/desktop.

Could also include some of the pitfalls we've encountered so far? Ie, what to do if port 5900 isn't free, some of the Windows troubleshooting, etc.

**Comment by ngreenwald** [comment]
Found out that port 5900 issue was a result of screensharing being enabled: https://apple.stackexchange.com/questions/314401/trying-to-close-open-port-5900-or-find-process-that-opened-it

**Comment by willgraf** [comment]
Closing this as it looks like #172 addressed most of the issue and the desktop build now lives in another repo.
