### ISSUE TITLE
Adjusting threshold for nuclear size

### ISSUE THREAD

**Issue by megleila** [vanvalenlab/deepcell-label#486]
**Is your feature request related to a problem? Please describe.**
I am trying out using Mesmer for segmentation through the Bodenmiller steinbock/IMCRtools pipeline and applying it on human kidney tissue samples.  I am finding that using the default training data for Mesmer is resulting in very small (1-2 pixel in size) debris being identified as nuclei.  This happens both for cell segmentation and for nuclear segmentation.  Looking at the source code available online (https://deepcell.readthedocs.io/en/latest/_modules/deepcell/applications/mesmer.html), I wondered whether you would recommend adjusting any of these parameters (ie nuclear radius) for this issue, or if you had another suggestion I could try?  Is this a common issue? 

**Describe the solution you'd like**
Suggested alteration to source code or training data to use to improve inappropriate labeling of debris as nuclei. 

**Describe alternatives you've considered**
We previously segmented using Ilastik/CellProfiler, but are looking for a more streamlined approach -- and additionally the segmentation of true nuclei does appear more accurate in DeepCell than it does in our former approach. 

**Additional context**
Deepcell segmentation including many very small debris identified as cells/nuclei
<img width="966" alt="image" src="https://github.com/vanvalenlab/deepcell-label/assets/135244025/6e04bc70-c66c-40b1-9442-466edf385fed">

Nuclear marker only
<img width="960" alt="image" src="https://github.com/vanvalenlab/deepcell-label/assets/135244025/635766af-b063-445d-b61b-e024d1e29639">

**Comment by ykevu** [comment]
Hi Megan,

I would suggest you reopen this issue at https://github.com/vanvalenlab/deepcell-tf/issues. This is the repo for DeepCell Label, the web application used for adding/editing labels to images, not for the DeepCell algorithms. 

If you have questions about manually editing your DeepCell segmentation outputs with DeepCell Label, I would be happy to answer them, however.
