### ISSUE TITLE
scale image display to fill available space

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#51]
The html canvas element is likely to remain the same size across different jobs, but npzs and trks might have a range of different sizes. Currently, browser caliban scales these files by 2 to display them. Preferably, the javascript load_file function would include the available canvas size as an arg so that upon initialization, the python object (ZStackReview or TrackReview) would scale to fit that size. Scaling is currently the only way we have to magnify the image (until a zoom feature can be implemented), so we should use it to the fullest extent we can.

**Comment by geneva-miller** [comment]
Looking closer, it appears that the canvas gets resized to match the size of the display (I think this happens in the main js files in the function load_file). With this way of doing things, the scale_factor is basically hardcoded as 2, and the size of the canvas will expand to fit whatever that size is.

My concern is that a larger file (for example, 1608x1608 pixels) would expand to be unreasonably large on the screen. I don't know if this would cause any slowdowns for drawing the image, but I think that having to scroll the page to reach part of the file is something we should avoid (since it will be important to see the displayed info in most cases). With that in mind, I think we should pick a single canvas size and stick with that (I think we could go larger than 600x400 but I don't know how large to go). That size would get passed to caliban.py when initializing the object to modify, and a scale factor would get set. For files larger than the canvas size, scale factor should remain at 1, but the rest of the image should be viewable by scrolling in the canvas. (Implementing that would be a precursor to zooming, but should not block us from making progress on curating small files. We will just have an image size limit at first.)

In general, having the ability to zoom in on a scrollable canvas is where I think we need to go with this, and taking a close look at scaling is where we should start with that.

**Comment by willgraf** [comment]
This was further updated with #154 but will remain open until the trk and zstack features are aligned.

**Comment by willgraf** [comment]
Is this resolved by #282?

Sounds like we were waiting to close until trk and npz files were handled the same way.
