### ISSUE TITLE
Unable to load images while using DeepCell-label locally

### ISSUE THREAD

**Issue by ArozHada** [vanvalenlab/deepcell-label#522]
**Describe the bug**
Hello, I can get DeepCell-label welcome page running locally but I am unable to upload any images. I cannot also open any example images locally. I get an error on my backend terminal saying 
"
X.ome.tiff not found in zip.
Loading all tiffs in zip.
y.ome.tiff not found in zip.
Loading all tiffs in zip.
Warning: JSON file divisions.json not found.
Warning: JSON file lineage.json not found.
Warning: JSON file cellTypes.json not found.
Warning: JSON file cells.json not found.
Warning: JSON file embeddings.json not found.
[2023-08-21 16:48:33,064] ERROR in blueprints: Encountered ValueError: axes do not match shape
Traceback (most recent call last):
  File "/Users/anaconda3/envs/deepcell_label_env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()

botocore.exceptions.ClientError: An error occurred (AuthorizationHeaderMalformed) when calling the PutObject operation: The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential."

I have also tried uploading a zip folder with tiffs but I encounter the same error. Is there any specific format for the upload of the images or did I miss something in my local installation? 

Furthermore, can I upload a segmentation mask along with the corresponding image?  

**To Reproduce**

1. Run frontend and backend as suggested in the documentation for local use. 
2. Upload any image when using the application locally
3. See error

**Expected behaviour**
Opening of the annotation studio

**Desktop (please complete the following information):**

- OS:  macOS
- Version [latest]
- Python Version [e.g. 3.9.17]

**Comment by rossbar** [comment]
In order to run locally, you will still need to provide a bucket that data will be uploaded to. URLs and credentials are [specified in the `.env` file.](https://github.com/vanvalenlab/deepcell-label/blob/main/backend/.env.example)

**Comment by ArozHada** [comment]
Is there any way to run Deepcell Label without using an aws bucket and using local storage?

**Comment by ykevu** [comment]
The backend codebase would have to be changed to allow for that, as it assumes that a bucket is provided. As far as I know an older version of DeepCell Label supported local usage without an AWS bucket, so another solution would be to roll back your clone to such a version (at the obvious cost of some bugs existing and none of the new features for cell types)

**Comment by ArozHada** [comment]
Ok, Thank you for the quick response. :)

**Comment by ykevu** [comment]
No problem--to be a little more specific, I started working on DCL just after the 0.4.0 release, which had already moved to AWS-only for local, so definitely don't try anything from then on
