### ISSUE TITLE
Cannot upload 16-bit, 4.6GB, 3.55X3.42mm, .tif of 29 channel multiplex image

### ISSUE THREAD

**Issue by smith6jt-cop** [vanvalenlab/deepcell-label#527]
**Describe the bug**
Getting "undefined" error after hitting upload button on website.

**To Reproduce**

Upload by drag and drop or by choosing file.
Choose any of the available dimension options in the dropdown menu.

**Expected behavior**
The file to upload.

**Screenshots**
The image I am trying to upload as it appears in FIJI:
![image](https://github.com/vanvalenlab/deepcell-label/assets/73438963/a83924cc-fb8c-4170-bb74-933dc9394998)
![image](https://github.com/vanvalenlab/deepcell-label/assets/73438963/b74333aa-891f-4c65-acc6-35c476da38d8)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version [e.g. 0.2]
- Python Version [e.g. 3.8.10]

**Additional context**
My image opens in QuPath as a single plane, single timepoint image with 29 channels.

**Comment by ykevu** [comment]
What is the dimension order of your image? It might be difficult to diagnose the problem without the file itself also, do you have a smaller example file of the same format?

**Comment by smith6jt-cop** [comment]
Thank you for your response.  I believe the dimension order is XYC although sometimes different programs interpret dimension order differently (see https://forum.image.sc/t/multichannel-ome-tiff-import-order-xyzct-vs-xyczt/45960) so I tried uploading with each available option in the dropdown menu.
[20_008-SP_CC2-B_11092020_reg001_chsNEWcropsmall.zip](https://github.com/vanvalenlab/deepcell-label/files/13026760/20_008-SP_CC2-B_11092020_reg001_chsNEWcropsmall.zip)

**Comment by rossbar** [comment]
From the OP it looks like this is a 9.4k x 9k pixel image; currently the maximum supported size by deepcell-label is 2048 x 2048 pixels.

**Comment by ykevu** [comment]
Since the smaller cropped image seems to work, I think @rossbar is right that this is an issue of exceeding the supported size.

**Comment by rossbar** [comment]
Sorry, I got my wires crossed a bit - the explicit 2048x2048 limitation is for deepcell.org, not label.deepcell.org. Nevertheless, this is almost certainly a data size issue. In terms of workarounds, pre-tiling the image and uploading the tiles separately is probably the easiest workaround (quadrants should work). We'd like to support arbitrarily large images but it's not on the immediate roadmap.
