### ISSUE TITLE
we should have more files in our test folder

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#55]
We should have several files in the test folder so we can check browser caliban functionality over a range of use cases. Some variables I'd like to make sure get included are:

- [ ] a range of image sizes

- [ ] different data types (trk, untracked movie as npz, zstack, single frame npz) with both nuclear and cytoplasmic images

- [ ] easy and difficult tasks

- [ ] files at various stages of completion (ie, things that would get fixed with different sets of tools, such as the bulk mode operations vs various pixel-level tools that we haven't implemented yet)

Each file in the test folder should be included in the dropdown list on the caliban website. We may want to include a way to say which features each file has (ie, test2.npz is multichannel cytoplasm zstack, uncorrected, with shape of (slices, y, x, channels)). Including comments along those lines in the code or the browser caliban readme may also be helpful. Files will likely get added to the test folder as we find them in the course of annotating data, and the list of useful test examples may change as time goes on.

**Comment by geneva-miller** [comment]
Added an npz of HeLa cytoplasm (shape of raw images is (45, 270, 320, 4) and there is 1 feature). Movie includes 1 fluorescent channel and 3 different phase channels. Annotations are model predictions and have many errors, including duplicate labels, incorrect shapes, and the occasional missed cell. This is an ideal npz for checking features on in the near future, since the other npzs from this set will likely make up the first several fig8 jobs we use browser Caliban for. May also be useful in future as a timelapse npz option (compared to zstack npzs). File is displayed as "test2.npz" in dropdown list on Caliban landing page.

**Comment by geneva-miller** [comment]
Added another npz (test3) of HeLa cytoplasm that is only 5 frames--this is size of HeLa movie pieces that will get launched to fig8. Annotations have many errors and have been relabeled so that each cell in each frame has a unique label--this may not be the labeling scheme annotations have when launched to fig8.

**Comment by tddough98** [comment]
We currently have 4 example files available on label.deepcell.org

- the example image on [deepcell.org/predict](https://deepcell.org/predict) for Mesmer with real Mesmer predictions with several errors artificially introduced
- a 3d zstack of an organoid
- a corrected 10 frame timelapse
- the same timelapse uncorrected

These example show a breadth of the datatypes and features that currently work with DeepCell Label, like tissue segmentation, 3d zstack segmentation, and tracking timelapses. The example Mesmer image has enough introduced errors to show how to use most segmentation tools, and the natural errors in the uncorrected timelapse show how to use the tracking controls.

Closing this issues as the current examples files demonstrate most current DeepCell Label features.
