### ISSUE TITLE
colormaps should be robust to different ranges of labels

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#74]
Eg, an image that has labels between 100 and 120 should be just as easy to look at as an image with labels between 0 and 20. Ideally, even labels that span a wide range of values (eg, if the labels in an image were [1, 5, 10, 50, 100, 500]) should be easy to tell apart.

I'd like to avoid having user-adjustable label colors in browser caliban as they exist in desktop caliban. Since browser caliban.py masks background with black, setting vmin = min(self.tracks) might be an easy step towards a solution. There may be additional ways we can improve the quality of the colormapping.

**Comment by ngreenwald** [comment]
We've run into this problem with desktop caliban. Ensuring that everything
gets sequentially relabeled after chopping prior to visualization took care
of the most egregious errors, but a more robust solution would be great!

**Comment by ngreenwald** [comment]
Update: even with a fairly small number of cells, the rendering is still an issue. The high 50s begin to approach pure white quite quickly, and are hard to distinguish from background in edit mode for npz.

**Comment by geneva-miller** [comment]
I think these issues may be solved in the next few weeks in browser mode due to some implementation differences. In the meantime, I might be able to throw together a desktop workaround for this situation. What I'm thinking is that the range of colors would be restricted to a span of ~20 labels, maybe even fewer. Scrolling the mouse wheel while viewing annotations would change the start and end points of the span. So at any given time, many of the labels would be either too dark or too light to distinguish from each other, but the labels in your working range would retain better separation from each other and remain rendered in color.

Do you think that would work to solve your rendering issues for the time being? If this approach sounds good to you we can try it on a new branch, I think I could put this together in a day or two.

**Comment by ngreenwald** [comment]
If it's going to be fixed in the near future I don't want to create significant extra work for you. 
What about only rendering 20 unique colors, no matter the number of labels? Something like the first 20 cells get unique colors, and then having the colors start over. Would that be less work than implementing a scroll wheel for us? Then as long as two cells aren't sharing a border, we it should get the job done.

**Comment by geneva-miller** [comment]
The scroll wheel already maps to some color adjustment stuff--I don't think it should be too much effort to rework. The two main updates to browser mode that need to happen before that's an option are adding advanced edit mode features and a way to zoom, and I'm not sure how long zoom will take to implement (especially with the holidays approaching).

I'll take a look at this in the next few days and let you know if/when I get something implemented.

**Comment by ngreenwald** [comment]
Got it, no worries! Zoom is also on our wish list :)

--Noah

**Comment by geneva-miller** [comment]
Could you email me an npz of mibi data? I'd like to get a feel for what values you're working with and what the display looks like before I push a workaround

**Comment by ngreenwald** [comment]
Definitely

**Comment by geneva-miller** [comment]
I've pushed a branch desktop/limit_annotation_color_range which I think should address your display issues for the time being. Basically, only ~20 labels at a time will have color (the others will be displayed as black if they're below the cutoff, and as white if they're above the cutoff), and which labels have color can be adjusted with the scroll wheel while viewing the annotations. Edit mode is the same way (only the annotations with color will be displayed as overlays). Additionally, the colors in edit mode will match the colors in the default annotation display mode, they'll be displayed with a little more opacity than they were before, and the brush preview is set to be permanently red to help keep it visible. 

Using this branch may make it a little more difficult to see the "big picture" of the annotations/catch things at a glance, and you'll need to pay more attention to adjusting the display as you work. Because of the drawback to seeing it at a glance, I'm not sure this will make it into master, but if desktop caliban changes on master I'll make sure to keep this branch updated. Let me know how this works for you, or if there's other adjustments to display that would help.

**Comment by ngreenwald** [comment]
Hi Geneva, 
Thanks so much! However, I'm not currently seeing the changes. I checked out the new branch and rebuilt the docker image. Is there something else I need to do? Here's what I see when I load the MIBI_Example.npz
![Screen Shot 2019-12-10 at 2 03 31 PM](https://user-images.githubusercontent.com/13770365/70573020-e23c6380-1b55-11ea-95e4-70ed7a6bfe3a.png)

**Comment by geneva-miller** [comment]
Hmm, I'm not sure what to tell you. I might poke around a little more with Docker and make sure you're actually using that branch, you should be seeing something more like:
![image](https://user-images.githubusercontent.com/45578681/70573441-d604d600-1b56-11ea-84e4-e0b3e33ef07c.png)
or with some adjustment:
![image](https://user-images.githubusercontent.com/45578681/70573476-ecab2d00-1b56-11ea-94ec-72fcbf2c71f2.png)

**Comment by ngreenwald** [comment]
So I went back to the master branch, and it seems like scrolling there already works for changing the labels! This is great, it'll be really useful for us to adjust. It sometimes freezes if we scroll too fast while in edit mode, it could be that the rendering is having to check something each time we scroll?

Thanks so much, this is a great patch. I think the long-term fix is to re-use the same maximally contrasted set of 15-20 colors, but for now this will definitely do the trick.

**Comment by geneva-miller** [comment]
Yes, scrolling in master changes vmax for the annotations but does not change vmin, which has drawbacks for rendering many labels. Yes, adjusting the scroll updates the composited image, which is slow, so it's recommended to make contrast changes outside of edit mode when you can.

Hopefully you can get that branch working since I think those changes will help show MIBI annotations better. I'll take another look later this evening and see if the same thing happens if I run the branch in Docker.

**Comment by ngreenwald** [comment]
Is this resolved in browser? On desktop, when I created 5 new labels, they were all given the same color: 
![image](https://user-images.githubusercontent.com/13770365/74309321-467acf80-4d1f-11ea-93e6-2f9b0a975331.png)

I think with MIBI data we're frequently going to have 40-50 cells in an image

**Comment by geneva-miller** [comment]
So in this attached image the labels are actually slightly different shades but are quite similar because they're in the same part of the colormap.

I think my plan with this is to disable the colormap adjustment with scroll wheel and add in another colormap for display options. In not-RGB mode you can cycle through some different colormaps using shift+up/down to view the raw data; I would likely be doing something similar for annotations, but with fewer colormaps. This would let us switch between the above colormap and one where similar values get very different colors. I think the only issue to consider is how to implement highlighting if some of the non-highlighted labels are also red.

**Comment by ngreenwald** [comment]
Totally! For RGB mode, I think it would be preferable to have a smaller number of very distinct colors that get reused, as long as they're not reused for physically adjacent labels. I'm not sure how demanding that would be to implement. From my perspective it's not crucial that every label have a distinct color, only that it's obvious when adjacent cells have different labels. 

My preference would be that the default rendering does a good enough job and doesn't require switching color maps, even if it gives distant cells the same color.

There are a couple ways that could be implement: shuffling around 20 colors randomly across the image, dividing the image into quadrants and reusing the map within each quadrant, etc. 

Honestly though, the rendering is already so much better than before that I'm fairly happy with how things are currently, it's been great!

**Comment by geneva-miller** [comment]
I think most of those things would be demanding to implement, and part of what I like about the default colormap is that it tends to make cell divisions obvious in timelapse data. I'm basically thinking I could put in this colormap as another option, though:

![image](https://user-images.githubusercontent.com/45578681/76039398-29da4d80-5f01-11ea-9f9f-1407fb35a7dd.png)

I don't think it guarantees that adjacent cells will have different color labels, but it makes it a lot more likely. And there should still be visually distinct highlighting.

**Comment by ngreenwald** [comment]
I really like that!

**Comment by geneva-miller** [comment]
Related: I'm going to delete the branch desktop/limit_annotation_color_range as neither of us needs it any longer to display labels clearly.

**Comment by geneva-miller** [comment]
Closing this issue as DCL now has several features that improve visualization of labels. (Labels that aren't sequential, or don't start from 1, can still be discussed in issue #73.) 

DCL now uses the [viridis colormap](https://matplotlib.org/stable/tutorials/colors/colormaps.html#sequential), so labels that are close in value will still be similar or identical in color.
![image](https://user-images.githubusercontent.com/45578681/165366887-9dfae1b0-11b8-4520-bc7f-0fe3bb7b4b05.png)

However, the highlighting and outline display options are sufficient for distinguishing labels of similar color:
![image](https://user-images.githubusercontent.com/45578681/165366555-1b6832d7-3f4b-497a-a7c7-6d0c95d0d621.png) vs. ![image](https://user-images.githubusercontent.com/45578681/165366595-658f2462-6842-42ce-8f20-a8a39ac9d0ea.png)
