### ISSUE TITLE
refine parent assignment in trk files

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#80]
Currently, the "parent" action for trk files will prevent duplicate daughters from being added to the daughters list of a parent cell (implemented in desktop in #36 and in browser in #78), but additional changes to the action could help it perform correctly/avoid bugs in a wider variety of cases.

- parent/daughter relationship should not be assigned if parent label ever appears in same frame as daughter label, or if parent label ever appears in movie again once daughter label has appeared (implemented for browser in #78)

- label should not be assigned as parent to itself (implemented for browser in #78)

- frame_div should be set to earliest frame that any daughter appears (for edge divisions, sometimes the second daughter appears in frame after the first daughter does, which can confuse frame_div assignment) (implemented for browser in #78)

- if a parent/daughter relationship is assigned incorrectly, and a new parent is assigned to the daughter cell(s), the daughter label should be cleared from the old, incorrect parent's lineage info

**Comment by willgraf** [comment]
Is this resolved by #282?
