### ISSUE TITLE
support cell type classification

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#82]
This is definitely a long-term request, but eventually we're going to want to train integrated models that not only predict segmentation, but also cell type classification at the same time. It would be great if we could do this within caliban. For example, in addition to each cell having a label, it would have a class category that could be adjusted by the user. For example, immune cells, tumor cells, and stromal cells. Perhaps a hotkey that cycles through a set of pre-defined cell classes that are defined in advance, similar to cell label, but with repeats.

**Comment by geneva-miller** [comment]
I think how this gets implemented in Caliban will depend on how the training data is structured, and I'm not sure what the best way to do that is. The two options that come to mind are: different features contain different cell types (working with multiple features is already supported in npz mode), or annotations come packaged with extra info (like we do with trk files), and that info gets edited with specialized functions. That second option would require a non-trivial amount of planning and development, I think.

When you start approaching that point, let's have a more in-depth conversation about it so we can figure out how we want to add that functionality.

**Comment by ngreenwald** [comment]
Definitely, sounds good!

**Comment by tddough98** [comment]
Cell type classification now covered in #251, #252, #253, #254, and #255
