### ISSUE TITLE
disable unused channels

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#96]
Is there a way that we can disable interactions with channels that don't contain data? For example, so that the brightness can't be adjusted, empty channels don't need to be cycled through to get to actual channels, and their values don't show up on the brightness settings? 

I think this would be useful to reduce confusion for annotators.

**Comment by ngreenwald** [comment]
This would also be helpful to increase the contrast when rendering the image. After I turn off the channels, the visualization of the remaining channels gets much better, to the point where regions that I previously marked as background are now obviously part of a cell because of better color visualization.

**Comment by geneva-miller** [comment]
Could you clarify what you mean by "empty channels"? I think I have some test files with channels that are mostly empty except for a few pixels of noise. If you are referring to channels that are truly empty, an example file would help me to see what you mean and implement a way around it.

I'm guessing that for what you're thinking, an empty channel (say channel 0, red) would be skipped over for brightness adjustment etc, but not dropped entirely. Eg if channel 0 were completely empty we still would display channel 1 as green, instead of making channel 1 the new red channel.

**Comment by ngreenwald** [comment]
Right. The current script allows you to specify a color for each channel. The way it does that is by ordering the channels according to what position gets rendered as what color. It inserts a mostly blank channel in between so that the actual channel containing data is rendered the appropriate color. 

The noise is artificial since I'm using a function I wrote for padding training data. 
Yeah, the goal is to keep the channels as the appropriate color, but remove them from being able to be cycled through, rendered etc.

**Comment by geneva-miller** [comment]
Okay, I think the simplest way to handle this on my end would be to use placeholder channels that don't contain any artificial noise. Then it is pretty straightforward to have Caliban check for zeros-only channels upon initialization, and skip those the way you describe.

A more complicated alternative would be passing in an additional argument that somehow specifies which channels to show. This could be something that indicates which channels to show and which to disable, or it could be something that specifies which color each channel should be (which would prevent the need for including empty channels). I'm reluctant to implement this solution in the near future but am open to working on this when my primary focus is on RGB Caliban again.

Would the first option work for you? That's something I could work on this week if I had an example file or two.

**Comment by ngreenwald** [comment]
The first option is totally fine, and likewise easy for me to change. I
don't see any short-term need for this to happen in desktop, I think it's
more needed for browser. I also think this can get put on the backburner
until we have at least a mockup of browser RGB, so I can start playing
around with making GIFs etc. Nice addition but not critical imo
