### ISSUE TITLE
grey out text when waiting for keyboard response

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#97]
It's sometimes hard to notice that caliban is waiting for you to hit s for save, or space to confirm, for a specific action that you've selected. It would be a nice visual queue for this if the descriptive text, such as channel, label, etc, would grey out when awaiting a response to more quickly guide the eye towards the bottom of the screen

**Comment by geneva-miller** [comment]
I'm a little wary of hiding the descriptive text as it may be more important to reference for higher-dimensional files. I'm open to other visual cues, perhaps drawing some white lines around the prompt message to draw the eye to what's in the new box? Although this is a relatively low priority it may be easy to accomplish once we decide on a visual indicator.

**Comment by ngreenwald** [comment]
Sorry, I meant grey out as in make it dimmer/lighter text shade, not hide it completely. Some sort of visual queue that it makes it obvious there is a prompt, but still allows you to see the information in the descriptive text.
